version: '3.8'

services:
  discord-bot:
    build: .
    container_name: tars-discord-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs